### ISSUE TITLE
Plans support basic auth? 

### ISSUE THREAD

**Issue by dannyZhou** [bvantagelimited/freeradius_exporter#24]
```shell
--web.config.file=/opt/prometheus-exporter/node_exporter/config.yml


```

/opt/prometheus-exporter/node_exporter/config.yml

```yml
basic_auth_users:
  ex: $a$aaaaaaaaaaaaaaaaaaaaaaaaa.

EOF
```
