### ISSUE TITLE
any chance of a docker image release?

### ISSUE THREAD

**Issue by axlroden** [bvantagelimited/freeradius_exporter#26]
```
name: Build and Push Docker Image

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/freeradius_exporter:${{ github.ref_name }}
```

Any chance you could add a github workflow ? 

(this is untested but i think it should be ok
